---
# List of packages to be installed via the yum package manager.
desktop:
  - gnome-panel
  - freenx
  - gnome-terminal
  - firefox
  - evince
programming:
  editors:
    - emacs
    - emacs-common
    - emacs-el
    - vim-X11
    - ctags
  version_control:
    - git
    - cvs
    - subversion
    - mercurial
    - bzr
  documentation:
  build:
    - swig
    - curl
    - curl-devel
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - gsl
    - gsl-devel
    - xfsprogs
    - glibc
    - glibc-devel
    - zip
    - zlib
    - zlib-devel
    - zziplib-devel
    - bzip2
    - bzip2-devel
    - gtk2
    - gtk2-devel
    - ncurses-devel
    - globus-openss
    - globus-openssl-devel
    - pcre
    - pcre-devel
    - readline
    - readline-devel
    - gcc
    - gcc-gfortran
    - gcc-c++
    - gcc44
    - gcc44-c++
    - gcc44-gfortran
  libraries:
    - lapack
    - lapack-devel
    - libgfortran
    - atlas
    - atlas-devel
    - blas
    - blas-devel
    - tcl-devel
    - tk-devel
    - ImageMagick
    - boost
    - boost-devel
    - openmpi
    - openmpi-devel
    - gd
    - gd-devel
    - libgnomecanvas
    - libgnomecanvas-devel
    - gnome-vfs2
    - gnome-vfs2-devel
    - libgnomeui
    - libgnomeui-devel
    - pango
    - pango-devel
  packaging:
    - unzip
  virtual:
  util:
    - tree
    - screen
  lang:
    - aspell
distributed:
  - rabbitmq-server
amazon:
python:
  meta:
    - python26
    - python26-devel
    - python26-distribute
ruby:
  - ruby
  - ruby-devel
  - rubygems
  - ruby-irb
  - rubygem-rake
r:
  - R
  - R-core
  - libRmath
  - libRmath-devel
perl: 
  - perl
java:
  - java-1.6.0-openjdk
  - java-1.6.0-openjdk-devel
  - ant
erlang:
  - erlang
  - erlang-devel
haskell:
  - ghc
databases:
  mysql:
    - mysql
    - mysql-devel
    - mysql-server
  postgres:
    - postgresql
    - postgresql-devel
    - postgresql-server
  sqlite:
    - sqlite
    - sqlite-devel
  document:
    - mongodb
    - mongodb-devel
    - couchdb
    - tokyocabinet
    - tokyocabinet-devel
  hdf:
    - hdf5
    #- hdf5-devel
math:
  - prover9
  - octave
  - octave-devel
viz:
  - graphviz
  - graphviz-devel
web:
  - httpd
  - httpd-devel
  - nginx
bio_general:
bio_search:
bio_alignment:
bio_nextgen:
  - samtools
bio_sequencing:
bio_annotation:
bio_microarray:
bio_visualization:
bio_utils:
phylogeny:
  all:
  needs_64bit:
