---
# List of packages to be installed via the package manager.
#
# This is derived from the Infochimps machetEC2 package:
#
# http://github.com/infochimps/machetec2
#
# and merged with packages from bioperl-max:
#
# http://fortinbras.us/bioperl-max/
#
# and biolinux:
#
# http://www.jcvi.org/cms/research/projects/jcvi-cloud-biolinux/included-software/
#
# Package names are the terminal symbols in the tree (the text on any
# line which begins with whitespace followed by a hypen and a space).
#
# The package list is organized taxonomically so that parts of it can
# be selectively installed/ignored. See main.yaml for top level configuration.
desktop:
  #Packages to support a remote desktop
  - gnome-panel
  - gnome-system-tools
  - synaptic
  - software-center
  - freenx
  - gnome-themes
  - gnome-backgrounds
  - gnome-terminal
  - firefox
  - evince
  - cloudbl-desktop
  - bio-linux-tutorials
programming:
  editors:
    - emacs
    - emacs-goodies-el
    - emacsen-common
    - vim
    - exuberant-ctags
  version_control:
    - git-core
    - cvs
    - subversion
    - mercurial
    - bzr
    - darcs
  documentation:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
  build:
    - swig
    - curl
    - libcurl4-openssl-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - libxslt1.1
    - libgsl0-dev
    - libgsl0ldbl
    - gsl-bin
    - xfsprogs
    - libc6-dev
    - libzip-dev
    - libbz2-dev
    - libgtk2.0-dev
    - libncurses5-dev
    - zlib1g-dev
    - libssl-dev
    - libpcre3-dev
    - libreadline5-dev
    - gcc 
    - g++
    - gfortran
    - stow
  libraries:
    - libatlas-dev
    - libblas-dev
    - liblapack-dev
    - tcl-dev
    - tk-dev
    - imagemagick
    - pdfjam
    - libsparsehash-dev
    - xvfb
    - libboost-dev
    - libboost-python-dev
    - libboost-thread-dev
    - boost-build
    - libopenmpi-dev 
    - libopenmpi1.3
    - openmpi-bin
    - libgd2-xpm
    - libgd2-xpm-dev
    - libgnomecanvas2-0
    - libgnomecanvas2-dev
    - libgnomevfs2-0
    - libgnomevfs2-dev
    - libgnomeui-0
    - libgnomeui-dev
    - libpango1.0-0
    - libpango1.0-dev
  packaging:
    - build-essential
    - devscripts
    - debhelper
    - dh-make
    - pbuilder
    - unzip
  virtual:
    - virtualbox-4.0
    - dkms
  util:
    - nfs-kernel-server
    - tree
    - screen
  lang:
    - aspell
    - dictionaries-common
    - libaspell-dev
# Note that the following Cloudera hadoop installation is for test
# purposes "inside the instance" only, Amazon already provides a
# production-ready Elastic MapReduce platform:
# http://aws.amazon.com/elasticmapreduce/
distributed:
  - rabbitmq-server
  - hadoop-0.20
  - hadoop-pig
  - hadoop-hive
  - libhdfs0-dev
  - hadoop-0.20-native
  - hadoop-0.20-pipes
  - hadoop-0.20-source
amazon:
  - s3cmd
  - ec2-ami-tools
  - ec2-api-tools
  - euca2ools
  - python-vm-builder-ec2
python:
  meta:
    - python
    - python-dev
    - python-setuptools
    - python-distutils-extra
  wrappers:
    - python-rpy
ruby:
  - ruby
  - ruby-dev
  - rubygems
  - ruby1.9.1
  - ruby1.9.1-dev
  - irb
  - ri
  - rdoc
  - rake
r:
  - r-base
  - r-base-core
  - r-base-core-ra
  - r-base-dev
  - r-base-html
perl: 
  - perl-base
  - perl
  - libperl-dev
  - perl-modules
  - perl-tk
  - parrot
  - parrot-devel
java:
  - sun-java6-bin
  - sun-java6-jre
  - sun-java6-jdk
  - openjdk-6-jdk
  - openjdk-6-jre
  - ant
  - libbiojava-java
  - libbiojava-java-demos
  - eclipse
  - maven2
  - libjline-java
  - libjhdf5-java
  - clojure
  - jruby
  - jython
  - scala
  - scala-library
erlang:
  - erlang
  - erlang-base
  - erlang-dev
  - erlang-examples
  - erlang-manpages
  - erlang-mode
haskell:
  - ghc6
  - libghc6-mtl-dev
  - libghc6-network-dev
  - libghc6-parsec2-dev
  - libghc6-parsec3-dev
  - libghc6-quickcheck1-dev
  - libghc6-quickcheck2-dev
  - libghc6-tagsoup-dev
  - libghc6-utf8-string-dev
  - libghc6-x11-dev
  - libghc6-x11-xft-dev
databases:
  mysql:
    - mysql-client
    - mysql-common
    - mysql-server
    - libmysqlclient15-dev
  postgres:
    - postgresql
    - postgresql-client
    - postgresql-plpython-8.4
    - postgresql-plperl-8.4
    - libpq-dev
  sqlite:
    - libsqlite3-0
    - libsqlite3-dev
    - sqlite3
  document:
    - libdb-dev
    - mongodb-stable
    - couchdb
    - tokyocabinet-bin
    - libtokyocabinet8
    - libtokyocabinet-dev
  hdf:
    - libhdf5-serial-1.8.4
    - libhdf5-serial-dev
math:
  - prover9
  - octave3.2
viz:
  - x11-apps
  - mayavi2
  - mtasc # for modest maps
  - graphviz
  - libgraphviz-dev
  - libgl1-mesa-dev
  - libgl1-mesa-dri
  - libgl1-mesa-glx
  - libglu1-mesa
  - libglu1-mesa-dev
web:
  - apache2
  - nginx
bio_general:
  - emboss
  - emboss-data
  - emboss-lib
  - primer3
  - readseq
  - bio-linux-taverna
  - bio-linux-xcut
bio_search:
  - blast2
  - hmmer
  - ncbi-tools-bin
  - bio-linux-blast+
  - bio-linux-blixem
  - bio-linux-fasta
  - bio-linux-mspcrunch
  - bio-linux-mview
  - bio-linux-nrdb
bio_alignment:
  - clustalw
  - exonerate
  - mafft
  - muscle
  - mummer
  - probcons
  - t-coffee
  - seaview
  - bio-linux-clustal
  - bio-linux-dotter
  - bio-linux-jalview
  - bio-linux-pfaat
  - bio-linux-prank
  - bio-linux-squint
  - bio-linux-wise2
bio_nextgen:
  - maq
  - samtools
bio_sequencing:
  - bio-linux-assembly-conversion-tools
  - bio-linux-cap3
  - bio-linux-dust
  - bio-linux-lucy
  - bio-linux-mira
  - bio-linux-mira-3rd-party
  - bio-linux-msatfinder
  - bio-linux-staden
  - bio-linux-stars
bio_annotation:
  - mcl
  - tigr-glimmer
  - bio-linux-act
  - bio-linux-artemis
  - bio-linux-big-blast
  - bio-linux-cd-hit
  - bio-linux-estscan
  - bio-linux-glimmer3
  - bio-linux-partigene
  - bio-linux-priam
  - bio-linux-prot4est
  - bio-linux-rbs-finder
  - bio-linux-transterm-hp
  - bio-linux-trnascan
# Package broken: - bio-linux-yamap
  - bio-linux-tetra
bio_microarray:
  - bio-linux-ocount
  - bio-linux-oligoarray
  - bio-linux-oligoarrayaux
bio_visualization:
  - rasmol
  - bio-linux-clcsequenceviewer
  - bio-linux-maxd
bio_utils:
  - bio-linux-das-prep
  - bio-linux-exchanger
  - bio-linux-genquery
  - bio-linux-keyring
  - bio-linux-base-directories
  - bio-linux-bldp-files
  - bio-linux-sampledata
  - bio-linux-sequin
  - bio-linux-taxinspector
  - bio-linux-themes-v5
phylogeny:
  all:
    - phylip
    - phyml
    - mrbayes
    - njplot
    - tree-puzzle
    - bio-linux-arb
    - bio-linux-coalesce
    - bio-linux-dendroscope
    - bio-linux-fastDNAml
    - bio-linux-fluctuate
    - bio-linux-forester
    - bio-linux-happy
    - bio-linux-mesquite
    - bio-linux-migrate
    - bio-linux-mrbayes-multi
    - bio-linux-mothur
    - bio-linux-paml
    - bio-linux-omegamap
    - bio-linux-qtlcart
    - bio-linux-recombine
    - bio-linux-splitstree
    - bio-linux-treeview
  needs_64bit:
    - bio-linux-fasttree
#
#
# To Add -- need packages
# from bioperl-max:
#   hyphy
#   bioperl-db
#   more perl modules
# from bio-linux:
#   Celera Assembler
#   lamarc - not available just now (22/6/10)
#   peptidemapper
#   pftools
#   transterm
# Others:
#   mdust
#   IGV
#   trimpoly
#   blast2go
#   sputnik: microsattelites
#   GenomeView
