---
# Configuration file defining perl libraries to install via CPAN
cpan:
# build
  - 'Locale::Maketext::Lexicon'
  - 'Module::Signature'
  - 'Build'
# dependencies
  - 'Algorithm::C3'
  - 'Algorithm::Diff'
  - 'Algorithm::Munkres'
  - 'AnyData'
  - 'Array::Compare'
  - 'Bit::Vector'
  - 'Bundle::LWP'
  - 'Cache'
  - 'Cairo'
  - 'Carp::Assert'
  - 'Carp::Clan'
  - 'CGI::Application'
  - 'CGI::Application::Plugin::Authentication'
  - 'CGI::Application::Plugin::Authorization'
  - 'CGI::Application::Plugin::TT'
  - 'CGI::Application::Plugin::HTDot'
  - 'CGI::Session'
  - 'Class::Accessor'
  - 'Class::C3'
  - 'Class::C3::XS'
  - 'Class::Data::Inheritable'
  - 'Class::Inspector'
  - 'Class::ISA'
  - 'Class::MOP'
  - 'Clone'
  - 'Config::Auto'
  - 'Config::IniFiles'
  - 'Config::Simple'
  - 'Convert::Binary::C'
  - 'Crypt::SSLeay'
  - 'Data::FormValidator'
  - 'Data::OptList'
  - 'Data::Stag'
  - 'Date::Calc'
  - 'Date::Manip'
  - 'DateTime::TimeZone'
  - 'DateTime::Locale'
  - 'DateTime'
  - 'Devel::GlobalDestruction'
  - 'Devel::StackTrace'
  - 'Digest::MD5'
  - 'Digest::HMAC'
  - 'Digest::SHA1'
  - 'Email::Valid'
  - 'Error'
  - 'Exception::Class'
  - 'Exception::Class::TryCatch'
  - 'ExtUtils::Manifest'
  - 'ExtUtils::ModuleMaker'
  - 'FCGI'
  - 'File::Copy::Recursive'
  - 'File::MMagic'
  - 'File::Slurp'
  - 'File::Which'
  - 'Font::AFM'
  - 'FreezeThaw'
  - 'GD::Graph'
  - 'GD::Text'
  - 'Glib'
  - 'Gtk2'
  - 'Gnome2::Canvas'
  - 'Gnome2::VFS'
  - 'Gnome2'
  - 'Graph'
  - 'GraphViz'
  - 'Heap'
  - 'HTML::Entities'
  - 'HTML::FillInForm'
  - 'HTML::FormatData'
  - 'HTML::HeadParser'
  - 'HTML::Parser'
  - 'HTML::Tagset'
  - 'HTML::Template'
  - 'HTML::Tree'
  - 'Image::Size'
  - 'Inline'
  - 'IO::Compress::Base'
  - 'IO::Compress::Bzip2'
  - 'IO::Compress::Lzf'
  - 'IO::Pty'
  - 'IO::Socket::SSL'
  - 'IO::String'
  - 'IO::Stringy'
  - 'IO::Unread'
  - 'IPC::Run'
  - 'IPC::ShareLite'
  - 'IPC::Signal'
  - 'Jcode'
  - 'List::MoreUtils'
  - 'Locale::gettext'
  - 'Log::Dispatch'
  - 'Mail::Internet'
  - 'Math::Derivative'
  - 'Math::Random'
  - 'Math::Spline'
  - 'MIME::Tools'
  - 'MIME::Types'
  - 'MLDBM'
  - 'Module::Build'
  - 'MRO::Compat'
  - 'Net::Daemon'
  - 'Net::DBus'
  - 'Net::DNS'
  - 'Net::Domain::TLD'
  - 'Net::IP'
  - 'Net::LibIDN'
  - 'Net::SSLeay'
  - 'OLE::Storage'
  - 'Pango'
  - 'Params::Util'
  - 'Params::Validate'
  - 'Parse::RecDescent'
  - 'Perl6::Junction'
  - 'Pod::Xhtml'
  - 'PostScript::File'
  - 'PostScript::TextBlock'
  - 'Proc::InvokeEditor'
  - 'Proc::WaitStat'
  - 'Regexp::Common'
  - 'RPC::XML'
  - 'Set::Scalar'
  - 'Scalar::Util'
  - 'Scope::Guard'
  - 'SOAP::Lite'
  - 'Sort::Naturally'
  - 'Spreadsheet::ParseExcel'
  - 'Spreadsheet::ParseExcel::Simple'
  - 'Spreadsheet::WriteExcel'
  - 'Storable'
  - 'SQL::Statement'
  - 'Statistics::Descriptive'
  - 'Sub::Exporter'
  - 'Sub::Install'
  - 'Sub::Name'
  - 'Sub::Uplevel'
  - 'SVG::Graph'
  - 'SVG'
  - 'Syntax::Highlight::Perl::Improved'
  - 'Task::Weaken'
  - 'Term::ReadKey'
  - 'Test::Exception'
  - 'Text::CharWidth'
  - 'Text::CSV'
  - 'Text::CSV_XS'
  - 'Text::Iconv'
  - 'Text::ParseWords'
  - 'Test::Harness'
  - 'Test::More'
  - 'Tie::IxHash'
  - 'Tree::DAG_Node'
  - 'Try::Tiny'
  - 'Unicode::Map'
  - 'UNIVERSAL::require'
  - 'URI::Escape'
  - 'UUID'
  - 'WWW::RobotRules'
  - 'XML::DOM'
  - 'XML::DOM::XPath'
  - 'XML::Filter::BufferText'
  - 'XML::LibXML '
  - 'XML::NamespaceSupport'
  - 'XML::Parser'
  - 'XML::Parser::PerlSAX'
  - 'XML::RegExp'
  - 'XML::SAX'
  - 'XML::SAX::Expat'
  - 'XML::SAX::Writer'
  - 'XML::Simple'
  - 'XML::Twig'
  - 'XML::Writer'
  - 'XML::XPathEngine'
  - 'XML::XPath'
  - 'YAML'
  - 'YAML::Syck'
  # Database drivers
  - 'DB_File'
  - 'DBI'
  - 'DBD::AnyData'
  - 'DBD::CSV'
  - 'DBD::mysql'
  - 'DBD::Pg'
  - 'DBD::SQLite'
  # Biome : these will definitely be added to over time
  - 'Moose'
  - 'MooseX::ClassAttribute'
  - 'MooseX::Types'
  - 'MooseX::Role::Parameterized'
  - 'MooseX::Aliases'
  # Biology
  - 'Ace'
  - 'Bio::ASN1::EntrezGene'
  - 'Bio::Graphics'
  - 'Bio::Phylo'
  - 'BioPerl'
  - 'Bio::Das'
  - 'Bio::GFF3::LowLevel'
# Currently have problems building on CentOS
#  - 'Convert::BinHex'
#  - 'XML'
#  - 'XML::LibXSLT'
#  - 'Modern::Perl'
#  These need samtools and Jim Kent's source trees so need to be done by hand
#  - 'Bio::DB::Sam'
#  - 'Bio::DB::BigFile'
